INSERT INTO PCAS_LOCALIZATION  (LAT , LNG , LOCALIZATION_CREATE_DATE , LOCALIZATION_LAST_UPDATE ) VALUES ('-365365','-654890',NOW(), NOW());
INSERT INTO PCAS_LOCALIZATION  (LAT , LNG , LOCALIZATION_CREATE_DATE , LOCALIZATION_LAST_UPDATE ) VALUES ('-064412','-612889',NOW(), NOW());
INSERT INTO PCAS_LOCALIZATION  (LAT , LNG , LOCALIZATION_CREATE_DATE , LOCALIZATION_LAST_UPDATE ) VALUES ('-309844','-112059',NOW(), NOW());

INSERT INTO PCAS_HOSPITAL (ADDRESS , CNPJ , HOSPITAL_CAPACITY_ID , HOSPITAL_CREATE_DATE , HOSPITAL_LAST_UPDATE , HOSPITAL_NAME , LOCALIZATION_ID) VALUES (125,'06545897545',56,NOW(),NOW(),'HOSPITAL SANTA DULCE',100);
INSERT INTO PCAS_HOSPITAL (ADDRESS , CNPJ , HOSPITAL_CAPACITY_ID , HOSPITAL_CREATE_DATE , HOSPITAL_LAST_UPDATE , HOSPITAL_NAME , LOCALIZATION_ID) VALUES (126,'32565891285',57,NOW(),NOW(),'HOSPITAL SÃO BENTO',101);
INSERT INTO PCAS_HOSPITAL (ADDRESS , CNPJ , HOSPITAL_CAPACITY_ID , HOSPITAL_CREATE_DATE , HOSPITAL_LAST_UPDATE , HOSPITAL_NAME , LOCALIZATION_ID) VALUES (127,'32566899874',58,NOW(),NOW(),'HOSPITAL NOSSA SENHORA DAS NEVES',102);

INSERT INTO PCAS_ADDRESS (ADDRESS_CREATE_DATE , ADDRESS_LAST_UPDATE , NUMBER , STREET ) VALUES (NOW(), NOW(),1390,'AV. DOM PEDRO II');
INSERT INTO PCAS_ADDRESS (ADDRESS_CREATE_DATE , ADDRESS_LAST_UPDATE , NUMBER , STREET ) VALUES (NOW(), NOW(),450,'AV. BAHIA');
INSERT INTO PCAS_ADDRESS (ADDRESS_CREATE_DATE , ADDRESS_LAST_UPDATE , NUMBER , STREET ) VALUES (NOW(), NOW(),9000,'RUA DE TODOS OS SANTOS');